### ISSUE TITLE
No input field

### ISSUE THREAD

**Issue by MattiSG** [totakoko/spotiblind#1]
Hi there,

Thanks for this app, it looks amazing!

I do manage to load a playlist, start playing and the display updates.
However, I see no input field for entering the name of the song, on Safari, Firefox, or Mobile Safari.
How can I enter the name of the song or artist when playing?  :)

Cheers!

**Comment by totakoko** [comment]
Hey!
You want to guess the song or artist name right? Unfortunately, this feature is not implemented. :(
If you have an idea on how to implement this, how to implement the fuzzy match (score threshold, global / per word), I'd be very grateful. :)

**Comment by MattiSG** [comment]
Yes, that was the intention. It would be really cool and bring this app closer to a full-fledged blind test  :)

For fuzzy matching, you probably want to use [Levenshtein distance](https://en.wikipedia.org/wiki/Levenshtein_distance). Several implementations are available on NPM, for example [that one](https://github.com/malcolm-sheridan/Levenshtein).

**Comment by totakoko** [comment]
For your information, I got delayed last week due to some typescript issues with vue and volar...
I'm on it now. I'll try to implement this this week.
I'll get back to you when the feature is released. :)

**Comment by MattiSG** [comment]
Amazing! Looking forward to it 😃

**Comment by totakoko** [comment]
I pushed a new version that contains an input field ! You can now guess the first artist and the track name.

Some information:
- For now, it's limited to the first artist only. We could guess more artists, but should one guess cover all artists in one shot or guess one artist at a time?
- You can't guess the artist and song name at the same time.
- You can make [one error per 10 characters](https://github.com/totakoko/spotiblind/blob/main/src/services/guess.ts#L68-L70) using the Levenshtein distance.
- The UX could get a lifting, especially compared to [this](https://whatthetune.com/)... :eyes: 

I look forward to your feedback. :smiley:

**Comment by MattiSG** [comment]
Just had a really cool blind test session thanks to this new feature 🤩 amazing, thank you so much!!
